[Rule]
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/core-direct.list,🎯 全球直连
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/ai-chatgpt.list,🤖 ChatGPT
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/ai-claude.list,🤖 Claude
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/ai-gemini.list,🤖 Gemini
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/social-telegram.list,📲 电报消息
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/stream-youtube.list,📹 油管视频
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/stream-netflix.list,🎥 奈飞视频
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/stream-disneyplus.list,🎥 迪士尼+
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/stream-bahamut.list,📺 巴哈姆特
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/social-bilibili.list,📺 哔哩哔哩
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/platform-google-fcm.list,📢 谷歌FCM
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/platform-onedrive.list,Ⓜ️ 微软云盘
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/platform-microsoft.list,Ⓜ️ 微软服务
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/platform-apple.list,🍎 苹果服务
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/game-global.list,🎮 游戏平台
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/music-netease.list,🎶 网易音乐
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/security-ads.list,🛑 广告拦截
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/security-privacy.list,🍃 应用净化
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/platform-cloudflare.list,☁️ CloudFlare
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/social-tiktok.list,📹 TikTok
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/stream-hbo.list,📺 HBO系列
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/stream-prime-video.list,🎥 亚马逊视频
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/stream-hulu.list,📺 Hulu
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/stream-dazn.list,📹 DAZN
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/game-steam-download.list,🎮 Steam下载
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/game-steam-web.list,🎮 Steam网页
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/ai-copilot.list,🤖 Copilot
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/security-reject.list,REJECT
RULE-SET,https://raw.githubusercontent.com/ifangng/loon-rules/main/config/rules/routing-proxy.list,🚀 节点选择
FINAL,🐟 漏网之鱼
